# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/recovery_db
spring.datasource.username=root
spring.datasource.password=Mehra@3101

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true