# 1. SERVER SETTINGS
# This tells Render exactly where to look for your app
server.port=8080

# 2. DATABASE SETTINGS
# Replace the placeholder with your actual Aiven/MySQL connection string
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# 3. HIBERNATE / JPA SETTINGS
# 'update' will create tables automatically if they don't exist
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 4. CONNECTION POOLING (Prevents 'Timed Out' crashes)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000

# Email Server Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mehrapriyanshu3101@gmail.com
spring.mail.password=jdjobbmoxxfgeeap
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
